<a href="https://colab.research.google.com/github/19PA1A04A1/Python-Basics/blob/master/Copy_of_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [46]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]
[1 2 3]
[1 2 3]


In [47]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [48]:
import numpy as np
np.arange(2,10,2)


array([2, 4, 6, 8])

array([2, 4, 6, 8])

array([2, 4, 6, 8])

In [49]:
import numpy as np
a=np.arange(15).reshape(3,5)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.itemsize)
print(a.size)
print(type(a))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int64
8
15
<class 'numpy.ndarray'>
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int64
8
15
<class 'numpy.ndarray'>
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int64
8
15
<class 'numpy.ndarray'>


In [50]:
import numpy as np
a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
import numpy as np
a=np.empty((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [52]:
import numpy as np
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
import numpy as np
np.full((3,3),6)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [54]:
import numpy as np
np.random.random((3,3))

array([[0.39553651, 0.04527981, 0.27120506],
       [0.46318057, 0.20820929, 0.13184721],
       [0.58368291, 0.84930634, 0.03453922]])

array([[0.12386844, 0.65333965, 0.95838622],
       [0.85351982, 0.2497594 , 0.45033237],
       [0.34952758, 0.17630624, 0.3441694 ]])

array([[0.0704378 , 0.06895715, 0.70738571],
       [0.43725741, 0.85928904, 0.95484299],
       [0.11998791, 0.82855347, 0.10066308]])

In [55]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(a)
print(b)
c=a-b
print(a)
print(b**2)
print(10*np.sin(a))
print(a<4)
a[0]+=3
print(a)

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[ 1  4  9 16]
[ 8.41470985  9.09297427  1.41120008 -7.56802495]
[ True  True  True False]
[4 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[ 1  4  9 16]
[ 8.41470985  9.09297427  1.41120008 -7.56802495]
[ True  True  True False]
[4 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[ 1  4  9 16]
[ 8.41470985  9.09297427  1.41120008 -7.56802495]
[ True  True  True False]
[4 2 3 4]


In [56]:
a=np.array([[1,2],[2,3]])
b=np.array([[5,6],[4,3]])
print(a)
print(b)
print(a*b)
print(a@b)
print(a.dot(b))
print(np.dot(a,b))

[[1 2]
 [2 3]]
[[5 6]
 [4 3]]
[[ 5 12]
 [ 8  9]]
[[13 12]
 [22 21]]
[[13 12]
 [22 21]]
[[13 12]
 [22 21]]
[[1 2]
 [2 3]]
[[5 6]
 [4 3]]
[[ 5 12]
 [ 8  9]]
[[13 12]
 [22 21]]
[[13 12]
 [22 21]]
[[13 12]
 [22 21]]
[[1 2]
 [2 3]]
[[5 6]
 [4 3]]
[[ 5 12]
 [ 8  9]]
[[13 12]
 [22 21]]
[[13 12]
 [22 21]]
[[13 12]
 [22 21]]


In [57]:
b=np.arange(12).reshape(3,4)
print(b)
print(b.sum())
print(b.sum(axis=0))
print(b.min(axis=1))
print(b.cumsum(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
66
[12 15 18 21]
[0 4 8]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
66
[12 15 18 21]
[0 4 8]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
66
[12 15 18 21]
[0 4 8]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [58]:
a=np.arange(10)**3
print(a)
print(a[2:4])
print(a[2])
print(a[-1])

[  0   1   8  27  64 125 216 343 512 729]
[ 8 27]
8
729
[  0   1   8  27  64 125 216 343 512 729]
[ 8 27]
8
729
[  0   1   8  27  64 125 216 343 512 729]
[ 8 27]
8
729


In [59]:
a=np.arange(12).reshape(3,4)
print(a)
print(a[1:3])
print(a[1:3,1:2])
print(a[-1,-3])
a.T

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[5]
 [9]]
9


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[5]
 [9]]
9


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[5]
 [9]]
9


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [60]:
a=np.array([[11,22,33],[44,55,66],[77,88,99]])
a
b=np.array([1,2,3])
b
c=a+b
c

array([[ 12,  24,  36],
       [ 45,  57,  69],
       [ 78,  90, 102]])

array([[ 12,  24,  36],
       [ 45,  57,  69],
       [ 78,  90, 102]])

array([[ 12,  24,  36],
       [ 45,  57,  69],
       [ 78,  90, 102]])

In [61]:
a=np.array([[1,2,3,4,5,6],[22,3,3,4,4,44]])
print(a)
np.hsplit(a,3)
np.vsplit(a,2)

[[ 1  2  3  4  5  6]
 [22  3  3  4  4 44]]


[array([[1, 2, 3, 4, 5, 6]]), array([[22,  3,  3,  4,  4, 44]])]

[[ 1  2  3  4  5  6]
 [22  3  3  4  4 44]]


[array([[1, 2, 3, 4, 5, 6]]), array([[22,  3,  3,  4,  4, 44]])]

[[ 1  2  3  4  5  6]
 [22  3  3  4  4 44]]


[array([[1, 2, 3, 4, 5, 6]]), array([[22,  3,  3,  4,  4, 44]])]

In [62]:
a=np.arange(15).reshape(3,5)**2
a

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [63]:
print(a.T)
print(a.shape)
print(a.ndim)

[[  0  25 100]
 [  1  36 121]
 [  4  49 144]
 [  9  64 169]
 [ 16  81 196]]
(3, 5)
2
[[  0  25 100]
 [  1  36 121]
 [  4  49 144]
 [  9  64 169]
 [ 16  81 196]]
(3, 5)
2
[[  0  25 100]
 [  1  36 121]
 [  4  49 144]
 [  9  64 169]
 [ 16  81 196]]
(3, 5)
2


In [64]:
a=np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [65]:
a=np.ones((5,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [66]:
import numpy as np
b=np.zeros((5,6))
b

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])