<a href="https://colab.research.google.com/github/19PA1A04A1/Python-Basics/blob/master/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [7]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [11]:
import numpy as np
np.arange(2,10,2)


array([2, 4, 6, 8])

In [27]:
import numpy as np
a=np.arange(15).reshape(3,5)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.itemsize)
print(a.size)
print(type(a))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int64
8
15
<class 'numpy.ndarray'>


In [28]:
import numpy as np
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
import numpy as np
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
import numpy as np
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
import numpy as np
np.full((3,3),6)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [35]:
import numpy as np
np.random.random((3,3))

array([[0.34647297, 0.60020785, 0.36090659],
       [0.38119458, 0.90719709, 0.9676034 ],
       [0.3041327 , 0.42937877, 0.31996773]])

In [50]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(a)
print(b)
c=a-b
print(a)
print(b**2)
print(10*np.sin(a))
print(a<4)
a[0]+=3
print(a)

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[ 1  4  9 16]
[ 8.41470985  9.09297427  1.41120008 -7.56802495]
[ True  True  True False]
[4 2 3 4]


In [55]:
a=np.array([[1,2],[2,3]])
b=np.array([[5,6],[4,3]])
print(a)
print(b)
print(a*b)
print(a@b)
print(a.dot(b))
print(np.dot(a,b))

[[1 2]
 [2 3]]
[[5 6]
 [4 3]]
[[ 5 12]
 [ 8  9]]
[[13 12]
 [22 21]]
[[13 12]
 [22 21]]
[[13 12]
 [22 21]]


In [63]:
b=np.arange(12).reshape(3,4)
print(b)
print(b.sum())
print(b.sum(axis=0))
print(b.min(axis=1))
print(b.cumsum(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
66
[12 15 18 21]
[0 4 8]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [73]:
a=np.arange(10)**3
print(a)
print(a[2:4])
print(a[2])
print(a[-1])

[  0   1   8  27  64 125 216 343 512 729]
[ 8 27]
8
729


In [75]:
a=np.arange(12).reshape(3,4)
print(a)
print(a[1:3])
print(a[1:3,1:2])
print(a[-1,-3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[[5]
 [9]]
9
